MBappy-404/Movie-ui

package-lock.json
package.json
src/components/HomePage/HomeBanner.tsx
src/components/HomePage/NewRelease.tsx
src/components/Shared/Navbar.tsx

update home page

---

package-lock.json
src/app/(HomeLayout)/profile/page.tsx
src/components/HomePage/Hero.tsx
src/components/HomePage/MovieDetails.tsx
src/components/HomePage/NewRelease.tsx
src/components/Shared/Navbar.tsx
src/components/ui/data-table.tsx

add profile

---

next.config.ts
package-lock.json
package.json
src/app/layout.tsx
src/app/login/page.tsx
src/app/register/page.tsx
src/components/Shared/Navbar.tsx
src/components/context/UserContext.tsx
src/components/modules/auth/login/LoginForm.tsx
src/components/modules/auth/login/loginValidation.ts
src/components/modules/auth/register/RegisterForm.tsx
src/components/modules/auth/register/registerValidation.ts
src/components/redux/features/wishListSlice.ts
src/components/redux/hooks.ts
src/components/redux/store.ts
src/components/types/user.ts
src/providers/Providers.tsx
src/providers/StoreProvider.tsx
src/services/AuthServices/index.ts

auth complete

---

src/components/Shared/movieDemo.tsx

 navbar crash fix

---

src/components/Shared/Navbar.tsx

navbar crash fix

---

next.config.ts
src/app/login/page.tsx
src/components/context/UserContext.tsx
src/components/modules/auth/profile/Userprofile.tsx
src/middleware.ts

 Middleware system ready

---

src/components/HomePage/TopArtists.tsx
src/components/modules/auth/login/LoginForm.tsx
src/components/modules/auth/register/RegisterForm.tsx
src/components/ui/input.tsx

update login and registration form

update login and registration form

---

src/components/modules/dashboard/user/add-user-dialog.tsx

 provider update

---

src/components/modules/auth/profile/Userprofile.tsx
src/components/modules/auth/register/RegisterForm.tsx

 somthing change

---

src/components/HomePage/Hero.tsx

add new fayshal

---

next.config.ts
src/app/(HomeLayout)/movies/[id]/page.tsx
src/components/HomePage/MovieDetails.tsx
src/components/Movies/MovieDetailsSkeleton.tsx
src/components/redux/features/content/contentApi.ts
src/components/redux/features/review/reviewApi.ts
src/components/redux/features/user/userApi.ts

add review and movie details update

add review and movie details update

---

src/components/HomePage/NewRelease.tsx
src/components/HomePage/TopArtists.tsx
src/components/HomePage/TopNews.tsx
src/components/HomePage/TrendingMovies.tsx
src/components/modules/auth/profile/Userprofile.tsx
src/components/modules/auth/register/RegisterForm.tsx
src/components/redux/features/content/contentApi.ts
src/services/AuthServices/index.ts

upadate and fix bugs on pages

---

src/app/(HomeLayout)/movies/[id]/page.tsx
src/components/HomePage/MovieDetails.tsx
src/components/modules/Comment/Comments.tsx
src/components/modules/Reviews/ReviewCard.tsx
src/components/redux/api/baseApi.ts
src/components/redux/features/comments/commentsApi.ts
src/components/redux/features/review/reviewApi.ts
src/middleware.ts

 comments part ready

---

next.config.ts
src/app/(DashboardLayout)/dashboard/content/page.tsx
src/app/(DashboardLayout)/dashboard/genre/page.tsx
src/app/(DashboardLayout)/dashboard/platform/page.tsx
src/app/layout.tsx
src/components/modals/UpdataPlatformModal.tsx
src/components/modals/UpdateContentModal.tsx
src/components/redux/api/baseApi.ts
src/components/redux/features/content/contentApi.ts
src/components/redux/features/genre/genreApi.ts
src/components/redux/features/platform/platformApi.ts
src/components/types/genre.ts
src/components/types/platform.ts
src/middleware.ts
src/services/AuthServices/index.ts

added CURD operations of contentCMS, GenreCMS, PlatformCMS

added CURD operations of contentCMS, GenreCMS, PlatformCMS

---

src/app/layout.tsx
src/components/HomePage/MovieDetails.tsx
src/components/modules/Comment/Comments.tsx
src/components/modules/Reviews/ReviewCard.tsx
src/components/redux/features/comments/commentsApi.ts

 reply part added

---

src/app/(HomeLayout)/invoice/success/page.tsx
src/components/HomePage/AllMovies.tsx

All movies page pagination ready

All movies page pagination ready

---

src/app/(HomeLayout)/invoice/success/page.tsx
src/components/HomePage/MovieDetails.tsx
src/components/Shared/Navbar.tsx
src/components/modules/auth/profile/Userprofile.tsx
src/components/redux/features/payment/paymentApi.ts
src/components/types/user.ts

add ssl comerze payment api for purchase movie

add ssl comerze payment api for purchase movie

---

src/components/modules/auth/profile/Userprofile.tsx
src/components/redux/features/payment/paymentApi.ts

update purchase history

---

src/components/Dashboardlayout/Header/Header.tsx

dashboard working fine

---

src/components/Dashboardlayout/Header/Header.tsx
src/components/Shared/Navbar.tsx
src/components/modules/auth/login/LoginForm.tsx
src/components/modules/auth/register/RegisterForm.tsx

 update something

---

src/app/(DashboardLayout)/dashboard/platformGenre/page.tsx
src/components/Dashboardlayout/Content/ManageContent.tsx
src/components/Dashboardlayout/Discount/DiscountManagement.tsx
src/components/Dashboardlayout/Genre/ManageGenre.tsx
src/components/Dashboardlayout/Header/Header.tsx
src/components/Dashboardlayout/OverviewStats/OverviewStats.tsx
src/components/Dashboardlayout/Platform/ManagePlatform.tsx
src/components/Dashboardlayout/Review/ManageReview.tsx
src/components/Dashboardlayout/User/ManageUser.tsx

updated dashboard layout

---

src/app/(DashboardLayout)/dashboard/platformGenre/page.tsx
src/app/(DashboardLayout)/dashboard/subscribers/page.tsx
src/app/(HomeLayout)/about/page.tsx
src/components/About/About.tsx
src/components/Dashboardlayout/Content/ManageContent.tsx
src/components/Dashboardlayout/Discount/DiscountManagement.tsx
src/components/Dashboardlayout/Genre/ManageGenre.tsx
src/components/Dashboardlayout/Header/Header.tsx
src/components/Dashboardlayout/Platform/ManagePlatform.tsx
src/components/Dashboardlayout/Review/ManageReview.tsx
src/components/Dashboardlayout/Sidebar/Sidebar.tsx
src/components/Dashboardlayout/Subscribers/Subscribers.tsx
src/components/Dashboardlayout/User/ManageUser.tsx
src/components/HomePage/Faq.tsx
src/components/HomePage/NewsLetter.tsx
src/components/HomePage/TopNews.tsx
src/components/HomePage/index.tsx
src/components/Shared/Navbar.tsx
src/components/redux/api/baseApi.ts
src/components/redux/features/subscribers/subscribersApi.ts

add category , subscribers, faq page

 add category , subscribers, faq page

---

src/app/(HomeLayout)/watchlist/page.tsx
src/components/Movies/MovieDetails.tsx
src/components/Movies/Movies/MovieDetails.tsx
src/components/Shared/Navbar.tsx
src/components/redux/features/cupon/cuponApi.ts
src/components/watchList/watchlist.tsx

add coupon intrgation

---

src/middleware.ts

updated middleware
